# Generated by Django 6.0.3 on 2026-03-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="devices_app.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="devices_app.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                ("threshold_id", models.AutoField(primary_key=True, serialize=False)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                (
                    "sensor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold",
                        to="devices_app.sensor",
                    ),
                ),
            ],
        ),
    ]
