# Generated by Django 6.0.3 on 2026-03-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Threshold",
            fields=[
                ("threshold_id", models.AutoField(primary_key=True, serialize=False)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "thresholds",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                ("data_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        db_column="device_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="devices_app.device",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_data",
                "ordering": ["-recorded_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.FloatField(blank=True, null=True)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "threshold",
                    models.ForeignKey(
                        blank=True,
                        db_column="threshold_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="monitoring_app.threshold",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
