# Generated by Django 6.0.3 on 2026-03-15 14:01

import django.db.models.deletion
from django.db import migrations, models


def migrate_sensor_relations_to_devices(apps, schema_editor):
    Device = apps.get_model("devices_app", "Device")
    Sensor = apps.get_model("devices_app", "Sensor")
    SensorData = apps.get_model("monitoring_app", "SensorData")
    Threshold = apps.get_model("monitoring_app", "Threshold")
    Alert = apps.get_model("monitoring_app", "Alert")

    unit_map = {
        "temperature": "C",
        "humidity": "%",
        "light": "lux",
    }

    sensors_by_device = {}
    for sensor in Sensor.objects.all():
        sensors_by_device.setdefault(sensor.device_id, []).append(sensor)

    for device in Device.objects.all():
        linked_sensors = sensors_by_device.get(device.pk, [])
        old_type = (device.device_type or "").strip().lower()
        if linked_sensors:
            primary_sensor = linked_sensors[0]
            device.device_type = "sensor"
            device.device_subtype = primary_sensor.sensor_type or device.device_subtype or "unknown"
        else:
            if old_type not in {"sensor", "actuator"}:
                device.device_type = "actuator"
                if not device.device_subtype or device.device_subtype == "unknown":
                    device.device_subtype = old_type or "generic"
            elif not device.device_subtype:
                device.device_subtype = "unknown"

        if (not device.unit) and device.device_subtype in unit_map:
            device.unit = unit_map[device.device_subtype]
        device.save(update_fields=["device_type", "device_subtype", "unit"])

    for entry in SensorData.objects.select_related("sensor", "sensor__device").all():
        if entry.sensor_id and entry.sensor.device_id:
            entry.device_id = entry.sensor.device_id
            if not entry.metric:
                entry.metric = entry.sensor.sensor_type or ""
            if not entry.unit:
                entry.unit = unit_map.get(entry.metric, entry.unit)
            entry.save(update_fields=["device", "metric", "unit"])

    latest_by_device = {}
    for entry in SensorData.objects.exclude(device_id=None).order_by("device_id", "-recorded_at", "-data_id"):
        latest_by_device.setdefault(entry.device_id, entry)

    for device_id, entry in latest_by_device.items():
        update_fields = []
        device = Device.objects.get(pk=device_id)
        if device.current_value != entry.value:
            device.current_value = entry.value
            update_fields.append("current_value")
        if entry.unit and device.unit != entry.unit:
            device.unit = entry.unit
            update_fields.append("unit")
        if device.last_reading_at != entry.recorded_at:
            device.last_reading_at = entry.recorded_at
            update_fields.append("last_reading_at")
        if not device.device_subtype or device.device_subtype == "unknown":
            device.device_subtype = entry.metric or device.device_subtype or "unknown"
            update_fields.append("device_subtype")
        if update_fields:
            device.save(update_fields=update_fields)

    threshold_by_sensor = {}
    for threshold in Threshold.objects.select_related("sensor", "sensor__device").all():
        if threshold.sensor_id and threshold.sensor.device_id:
            threshold.device_id = threshold.sensor.device_id
            threshold.save(update_fields=["device"])
            threshold_by_sensor[threshold.sensor_id] = threshold.pk

    for alert in Alert.objects.select_related("sensor", "sensor__device").all():
        if alert.sensor_id and alert.sensor.device_id:
            metric = alert.sensor.sensor_type or ""
            alert.device_id = alert.sensor.device_id
            alert.metric = metric
            if alert.sensor_id in threshold_by_sensor:
                alert.threshold_id = threshold_by_sensor[alert.sensor_id]
            if not alert.unit:
                alert.unit = unit_map.get(metric, alert.unit)
            if not alert.metadata:
                alert.metadata = {}
            if metric:
                alert.metadata.setdefault("metric", metric)
            if alert.sensor_id:
                alert.metadata.setdefault("legacy_sensor_id", alert.sensor_id)
            alert.save(update_fields=["device", "metric", "threshold", "unit", "metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("devices_app", "0002_device_current_value_device_description_and_more"),
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="actual_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="devices_app.device",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="alert",
            name="metric",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="alert",
            name="target_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_alerts",
                to="devices_app.device",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="threshold",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="monitoring_app.threshold",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="threshold_direction",
            field=models.CharField(
                blank=True,
                choices=[("low", "Below minimum"), ("high", "Above maximum")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="threshold_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="triggered_action",
            field=models.CharField(
                choices=[
                    ("none", "No action"),
                    ("turn_on", "Turn on"),
                    ("turn_off", "Turn off"),
                    ("toggle", "Toggle"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_data",
                to="devices_app.device",
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="metric",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="threshold",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threshold",
                to="devices_app.device",
            ),
        ),
        migrations.AddField(
            model_name="threshold",
            name="target_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trigger_thresholds",
                to="devices_app.device",
            ),
        ),
        migrations.AddField(
            model_name="threshold",
            name="trigger_action",
            field=models.CharField(
                choices=[
                    ("none", "No action"),
                    ("turn_on", "Turn on"),
                    ("turn_off", "Turn off"),
                    ("toggle", "Toggle"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_sensor_relations_to_devices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="alert",
            name="sensor",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="sensor",
        ),
        migrations.RemoveField(
            model_name="threshold",
            name="sensor",
        ),
    ]
