# Generated by Django 6.0.3 on 2026-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="threshold",
            name="require_motion",
            field=models.BooleanField(default=True),
        ),
    ]
