# Generated by Django 6.0.3 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_app", "0003_alter_device_options_alter_sensor_options_and_more"),
        (
            "monitoring_app",
            "0002_remove_alert_sensor_remove_sensordata_sensor_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"managed": True, "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sensordata",
            options={"managed": True, "ordering": ["-recorded_at"]},
        ),
        migrations.AlterModelOptions(
            name="threshold",
            options={"managed": True},
        ),
        migrations.RemoveField(
            model_name="alert",
            name="actual_value",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="device",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="metric",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="target_device",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="threshold",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="threshold_direction",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="threshold_value",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="triggered_action",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="device",
        ),
        migrations.RemoveField(
            model_name="sensordata",
            name="metric",
        ),
        migrations.RemoveField(
            model_name="threshold",
            name="device",
        ),
        migrations.RemoveField(
            model_name="threshold",
            name="target_device",
        ),
        migrations.RemoveField(
            model_name="threshold",
            name="trigger_action",
        ),
        migrations.AddField(
            model_name="alert",
            name="sensor",
            field=models.ForeignKey(
                blank=True,
                db_column="sensor_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="devices_app.sensor",
            ),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="sensor",
            field=models.ForeignKey(
                blank=True,
                db_column="sensor_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_data",
                to="devices_app.sensor",
            ),
        ),
        migrations.AddField(
            model_name="threshold",
            name="sensor",
            field=models.ForeignKey(
                blank=True,
                db_column="sensor_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thresholds",
                to="devices_app.sensor",
            ),
        ),
        migrations.AlterModelTable(
            name="alert",
            table="alerts",
        ),
        migrations.AlterModelTable(
            name="sensordata",
            table="sensor_data",
        ),
        migrations.AlterModelTable(
            name="threshold",
            table="thresholds",
        ),
    ]
