# Generated by Django 6.0.3 on 2026-04-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring_app", "0002_threshold_require_motion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threshold",
            name="require_motion",
            field=models.BooleanField(default=False),
        ),
    ]
