# Generated by Django 6.0.3 on 2026-03-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                ("rule_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(default=True)),
                ("action", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "automation_rules",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IsMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "is_monitor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=50)),
                ("schedule_time", models.TimeField()),
                ("repeat_type", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "schedule",
                "managed": True,
            },
        ),
    ]
