# Generated by Django 6.0.3 on 2026-03-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=50)),
                ("schedule_time", models.TimeField()),
                ("repeat_type", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="devices_app.device",
                    ),
                ),
            ],
        ),
    ]
