# Generated by Django 5.2.12 on 2026-03-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('schedule_time', models.TimeField()),
                ('repeat_type', models.CharField(choices=[('ONCE', 'Một lần'), ('DAILY', 'Hàng ngày'), ('WEEKLY', 'Hàng tuần'), ('MONTHLY', 'Hàng tháng')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices_app.device')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
