# Generated by Django 6.0.3 on 2026-03-15 14:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation_app", "0001_initial"),
        ("building_app", "0003_userroompermission"),
        ("devices_app", "0002_device_current_value_device_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="schedule",
            name="days_of_week",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="schedule",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="schedule",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="building_app.room",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="scope_type",
            field=models.CharField(
                choices=[("device", "Device"), ("room", "Room")],
                default="device",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="devices_app.device",
            ),
        ),
    ]
