# Generated by Django 6.0.3 on 2026-03-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("automation_app", "0001_initial"),
        ("building_app", "0001_initial"),
        ("devices_app", "0001_initial"),
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationrule",
            name="threshold",
            field=models.ForeignKey(
                blank=True,
                db_column="threshold_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules",
                to="monitoring_app.threshold",
            ),
        ),
        migrations.AddField(
            model_name="ismonitor",
            name="device",
            field=models.ForeignKey(
                db_column="device_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitor_rules",
                to="devices_app.device",
            ),
        ),
        migrations.AddField(
            model_name="ismonitor",
            name="rule",
            field=models.ForeignKey(
                db_column="rule_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitor_devices",
                to="automation_app.automationrule",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="room",
            field=models.ForeignKey(
                blank=True,
                db_column="room_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="building_app.room",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ismonitor",
            unique_together={("device", "rule")},
        ),
    ]
