# Generated by Django 6.0.3 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation_app", "0002_schedule_created_at_schedule_days_of_week_and_more"),
        ("devices_app", "0003_alter_device_options_alter_sensor_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"managed": True},
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="days_of_week",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="room",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="scope_type",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="device",
            field=models.ForeignKey(
                blank=True,
                db_column="device_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="devices_app.device",
            ),
        ),
        migrations.AlterModelTable(
            name="schedule",
            table="schedule",
        ),
    ]
