"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users_app',
    'auth_app',
    'building_app',
    'devices_app',
    'monitoring_app',
    'automation_app',
    'logs_app',
    'dashboard_app',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'channels',
    'iot_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_engine = os.environ.get("DB_ENGINE", "django.db.backends.sqlite3")

# Khi dùng SQLite3 (dev), Django tự tạo bảng qua migrate.
# Khi dùng PostgreSQL (prod), bảng do schema ngoài quản lý nên managed=False.
MANAGED_DB_TABLES = (_db_engine == "django.db.backends.sqlite3")

if _db_engine == "django.db.backends.sqlite3":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.environ.get("DB_NAME"),
            'USER': os.environ.get("DB_USER"),
            'PASSWORD': os.environ.get("DB_PASSWORD"),
            'HOST': os.environ.get("DB_HOST"),
            'PORT': os.environ.get("DB_PORT"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ─── ASGI / WebSocket ───────────────────────────────────────────
ASGI_APPLICATION = 'config.asgi.application'

# Channel layer: dùng InMemory khi dev (không cần Redis)
# Khi deploy production: đổi sang RedisChannelLayer (bình luận bên dưới)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        # Production với Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {'hosts': [('127.0.0.1', 6379)]},
    }
}

# ─── CoreIoT integration config ───────────────────────────────────────────────
COREIOT_ENABLED = os.environ.get('COREIOT_ENABLED', 'False') == 'True'
COREIOT_BASE_URL = os.environ.get('COREIOT_BASE_URL', 'https://app.coreiot.io')
COREIOT_LOGIN_URL = os.environ.get('COREIOT_LOGIN_URL', '')
COREIOT_EMAIL = os.environ.get('COREIOT_EMAIL', '')
COREIOT_PASSWORD = os.environ.get('COREIOT_PASSWORD', '')
COREIOT_ACCESS_TOKEN = os.environ.get('COREIOT_ACCESS_TOKEN', '')
COREIOT_AUTH_HEADER = os.environ.get('COREIOT_AUTH_HEADER', 'Authorization')
COREIOT_AUTH_PREFIX = os.environ.get('COREIOT_AUTH_PREFIX', 'Bearer ')
COREIOT_TIMEOUT_SECONDS = int(os.environ.get('COREIOT_TIMEOUT_SECONDS', 10))

COREIOT_DEVICE_ID = os.environ.get('COREIOT_DEVICE_ID', '')
COREIOT_TELEMETRY_URL_TEMPLATE = os.environ.get('COREIOT_TELEMETRY_URL_TEMPLATE', '')
COREIOT_SETSTATE_URL_TEMPLATE = os.environ.get('COREIOT_SETSTATE_URL_TEMPLATE', '')
COREIOT_SETSTATE_MODE = os.environ.get('COREIOT_SETSTATE_MODE', 'rpc')
COREIOT_SETSTATE_METHOD = os.environ.get('COREIOT_SETSTATE_METHOD', 'setState')
COREIOT_SETSTATE_VALUE_METHOD = os.environ.get('COREIOT_SETSTATE_VALUE_METHOD', 'setValue')

COREIOT_BRIGHTNESS_KEY = os.environ.get('COREIOT_BRIGHTNESS_KEY', 'brightness')
COREIOT_FAN_SPEED_KEY = os.environ.get('COREIOT_FAN_SPEED_KEY', 'fan_speed')
COREIOT_TEMPERATURE_KEY = os.environ.get('COREIOT_TEMPERATURE_KEY', 'temperature')
COREIOT_HUMIDITY_KEY = os.environ.get('COREIOT_HUMIDITY_KEY', 'humidity')
COREIOT_LIGHT_KEY = os.environ.get('COREIOT_LIGHT_KEY', 'light')
COREIOT_MOTION_KEY = os.environ.get('COREIOT_MOTION_KEY', 'motion')
COREIOT_TELEMETRY_KEYS = [
    COREIOT_BRIGHTNESS_KEY,
    COREIOT_FAN_SPEED_KEY,
    COREIOT_TEMPERATURE_KEY,
    COREIOT_HUMIDITY_KEY,
    COREIOT_LIGHT_KEY,
    COREIOT_MOTION_KEY,
]

COREIOT_LOCAL_LIGHT_ACTUATOR_ID = os.environ.get('COREIOT_LOCAL_LIGHT_ACTUATOR_ID', '')
COREIOT_LOCAL_FAN_ACTUATOR_ID = os.environ.get('COREIOT_LOCAL_FAN_ACTUATOR_ID', '')
COREIOT_LOCAL_TEMPERATURE_SENSOR_ID = os.environ.get('COREIOT_LOCAL_TEMPERATURE_SENSOR_ID', '')
COREIOT_LOCAL_HUMIDITY_SENSOR_ID = os.environ.get('COREIOT_LOCAL_HUMIDITY_SENSOR_ID', '')
COREIOT_LOCAL_LIGHT_SENSOR_ID = os.environ.get('COREIOT_LOCAL_LIGHT_SENSOR_ID', '')
COREIOT_LOCAL_MOTION_SENSOR_ID = os.environ.get('COREIOT_LOCAL_MOTION_SENSOR_ID', '')
COREIOT_SYNC_INTERVAL_SECONDS = int(os.environ.get('COREIOT_SYNC_INTERVAL_SECONDS', 2))
COREIOT_AUTO_SYNC_ON_RUNSERVER = os.environ.get('COREIOT_AUTO_SYNC_ON_RUNSERVER', 'True') == 'True'

# ─── CORS - cho phép FE (Vite dev server) gọi BE ───────────────
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True

# drf-spectacular (Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Smart Home API',
    'DESCRIPTION': 'API quản lý thiết bị nhà thông minh',
    'VERSION': '1.0.0',
}

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
