# Generated by Django 6.0.3 on 2026-03-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices_app", "0001_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=255)),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="devices_app.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="users_app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-action_time"],
            },
        ),
    ]
