# Generated by Django 5.2.12 on 2026-03-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices_app', '0001_initial'),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices_app.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.user')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
    ]
