# Generated by Django 6.0.3 on 2026-03-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices_app', '0001_initial'),
        ('users_app', '0001_initial'),
        ('logs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(default='system', max_length=32),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('device', 'Device'), ('system', 'System')], default='system', max_length=16),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='devices_app.device'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users_app.user'),
        ),
    ]
