# Generated by Django 6.0.3 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_app", "0003_alter_device_options_alter_sensor_options_and_more"),
        ("logs_app", "0002_activitylog_source_category_details_metadata_and_more"),
        ("users_app", "0003_alter_role_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"managed": True, "ordering": ["-action_time"]},
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="details",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="source",
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="device",
            field=models.ForeignKey(
                blank=True,
                db_column="device_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="devices_app.device",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="users_app.user",
            ),
        ),
        migrations.AlterModelTable(
            name="activitylog",
            table="activity_log",
        ),
    ]
