# Generated by Django 6.0.3 on 2026-03-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "device_type",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(max_length=255)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="building_app.room",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "managed": True,
            },
        ),
    ]
