# Generated by Django 6.0.3 on 2026-03-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(max_length=255)),
                ("device_type", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="building_app.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("sensor_id", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_type", models.CharField(max_length=50)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="devices_app.device",
                    ),
                ),
            ],
        ),
    ]
