# Generated by Django 6.0.3 on 2026-03-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="current_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="device",
            name="device_subtype",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddField(
            model_name="device",
            name="last_reading_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[("sensor", "Sensor"), ("actuator", "Actuator")], max_length=16
            ),
        ),
    ]
