# Generated by Django 6.0.3 on 2026-03-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices_app", "0001_initial"),
        ("monitoring_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="threshold",
            field=models.ForeignKey(
                blank=True,
                db_column="threshold_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="monitoring_app.threshold",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_column="type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="devices_app.devicetype",
            ),
        ),
    ]
