# Generated by Django 6.0.3 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building_app", "0004_alter_floor_options_alter_room_options_and_more"),
        ("devices_app", "0002_device_current_value_device_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={"managed": True},
        ),
        migrations.RemoveField(
            model_name="device",
            name="current_value",
        ),
        migrations.RemoveField(
            model_name="device",
            name="description",
        ),
        migrations.RemoveField(
            model_name="device",
            name="device_subtype",
        ),
        migrations.RemoveField(
            model_name="device",
            name="last_reading_at",
        ),
        migrations.RemoveField(
            model_name="device",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="device",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="device",
            name="room",
            field=models.ForeignKey(
                db_column="room_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="building_app.room",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="device",
            field=models.ForeignKey(
                db_column="device_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="devices_app.device",
            ),
        ),
        migrations.AlterModelTable(
            name="device",
            table="devices",
        ),
        migrations.AlterModelTable(
            name="sensor",
            table="sensors",
        ),
    ]
