# Generated by Django 6.0.3 on 2026-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="brightness",
            field=models.IntegerField(default=0),
        ),
    ]
