# Generated by Django 6.0.3 on 2026-03-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("floor_id", models.AutoField(primary_key=True, serialize=False)),
                ("floor_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "floors",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                (
                    "floor",
                    models.ForeignKey(
                        db_column="floor_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="building_app.floor",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RoomManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_column="room_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_managements",
                        to="building_app.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_managements",
                        to="users_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "room_managements",
                "managed": True,
                "unique_together": {("user", "room")},
            },
        ),
    ]
