# Generated by Django 6.0.3 on 2026-03-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("floor_id", models.AutoField(primary_key=True, serialize=False)),
                ("floor_name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="users_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=255)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="building_app.floor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="users_app.user",
                    ),
                ),
            ],
        ),
    ]
