# Generated by Django 6.0.3 on 2026-03-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building_app", "0001_initial"),
        ("users_app", "0002_alter_user_role_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="floor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floors",
                to="users_app.user",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="users_app.user",
            ),
        ),
    ]
