# Generated by Django 6.0.3 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building_app", "0003_userroompermission"),
        ("users_app", "0003_alter_role_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floor",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"managed": True},
        ),
        migrations.RemoveField(
            model_name="floor",
            name="level",
        ),
        migrations.AlterField(
            model_name="floor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floors",
                to="users_app.user",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="floor",
            field=models.ForeignKey(
                db_column="floor_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="building_app.floor",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="users_app.user",
            ),
        ),
        migrations.AlterModelTable(
            name="floor",
            table="floors",
        ),
        migrations.AlterModelTable(
            name="room",
            table="rooms",
        ),
        migrations.DeleteModel(
            name="UserRoomPermission",
        ),
    ]
