# Generated by Django 6.0.3 on 2026-03-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoTToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Ghi chú (tên board, ESP32...)",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iot_token",
                        to="devices_app.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "IoT Token",
            },
        ),
    ]
