# Generated by Django 6.0.3 on 2026-03-17 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "roles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="role_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users_app.role",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
    ]
