# Generated by Django 6.0.3 on 2026-03-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users_app.role",
            ),
        ),
    ]
