# Generated by Django 6.0.3 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_alter_user_role_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role_id",
            field=models.ForeignKey(
                blank=True,
                db_column="role_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users_app.role",
            ),
        ),
        migrations.AlterModelTable(
            name="role",
            table="roles",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
